print("Create your character!\n")
name = input("What is your character called?\n")
age = input("How old is your character?\n")
strengths = input("What are your character's strengths?\n")
weaknesses = input("What are your character's weaknesses?\n")
print("Your character's name is", name)
print("Your character's name is", age, "years old")
print("Strengths:", strengths)
print("Weaknesses:", weaknesses)
print(name, "says, 'Thanks for creating me!'")
